### ISSUE TITLE
CKAN 2.11 Compatiblity

### ISSUE THREAD

**Issue by twdbben** [data-govt-nz/ckanext-security#90]
I am working on upgrading to CKAN 2.11 (from 2.10) and am curious if anyone is using ckanext-security with CKAN 2.11.

Upon initial upgrade we are still able to login with ckanext-security but we are seeing an `AttributeError: 'RedisSession' object has no attribute 'invalidate'` error when attempting to logout.

I can provide more detail but first just wanted to get a sanity check on whether we should expect ckanext-security to work with a CKAN 2.11 install generally.

Thank you!

**Comment by markstuart** [comment]
Hi Ben,

I've recently upgraded the site we maintain and use this extension in to 2.10.9, but have no immediate plans to update to 2.11 as there are a bunch of changes between 2.10 and 2.11 that affect other extensions used in that site as well, and I see that it is likely to be a large chunk of work.

If you have any luck upgrading this extension for your site, please raise a pull request with the changes and I'll try to get some time to test it against a base CKAN 2.11 site as well.

Cheers,
Mark

**Comment by twdbben** [comment]
Mark,

I'll let you know how it goes. So far, with the exception of the error I'm seeing when logging out, it seems to be mostly working - but I still need to do a lot of testing.

Thanks,
~Ben
