### PR TITLE
Fix CKAN 2.11 compatibility: use session.clear() for Flask-Session

### LINKED ISSUE #90: CKAN 2.11 Compatiblity
I am working on upgrading to CKAN 2.11 (from 2.10) and am curious if anyone is using ckanext-security with CKAN 2.11.

Upon initial upgrade we are still able to login with ckanext-security but we are seeing an `AttributeError: 'RedisSession' object has no attribute 'invalidate'` error when attempting to logout.

I can provide more detail but first just wanted to get a sanity check on whether we should expect ckanext-security to work with a CKAN 2.11 install generally.

Thank you!

### PR DESCRIPTION
**Pull request by maxwellyoung**
## Summary

Fixes #90 - CKAN 2.11 replaced Beaker with Flask-Session for session management. The `logout()` method was calling `session.invalidate()` which doesn't exist in Flask-Session, causing an `AttributeError: 'RedisSession' object has no attribute 'invalidate'` error.

## Solution

Added a CKAN version check to use the appropriate session termination method:
- **CKAN 2.11+**: `session.clear()` (Flask-Session API)
- **CKAN <2.11**: `session.invalidate()` (Beaker API)

This maintains backward compatibility with older CKAN versions while fixing the logout error in 2.11+.

## Changes

- `ckanext/security/plugin/flask_plugin.py`: Import toolkit, add version-conditional logout logic

## References

- CKAN 2.11 migration notes: https://docs.ckan.org/en/2.11/changelog.html#migration-notes-2-11
- Related work by @twdbben: https://github.com/TNRIS/ckanext-security/commit/e449fd48254a69f6c282d53bc784563dc9c3a60a

### CODE REVIEW

**Comment by markstuart** [comment]
Thanks for this, I've added it into #92 and that will get shipped in the near future.
