### ISSUE TITLE
ckanext error while installing dependencies 

### ISSUE THREAD

**Issue by Team1-epat** [data-govt-nz/ckanext-security#70]
Tried to load the ckanext-security into ckan2.10 and used Dockerfile to install the .whl files for the following

- pyotp==2.6.0
- python-magic==0.4.24
- redis==3.5.3
- WebOb==1.8.7
- repoze.who==2.4
- six==1.16.0

In the requirement.txt, it also stated to install the "beaker-py". I have tried to install "beaker-py" and its dependencies, but encountered error when I install the dependencies, error message: **ERROR: pydantic_core-2.16.2-cpp311-cp311-musllinux_1_1_x86_64.whl is not a supported wheel on this platform**.

May I know how can I overcome this issue? 

If I install all the above mentioned python modules and without the beaker-py, I have encountered this error during ckan program startup: **ImportError : cannot import name 'UsernamePasswordAuthenticator' from 'ckan.lib.authenticator' (/srv/app/src/ckan/ckan/lib/authenticator.py) **, how can I resolve this error?

**Comment by markstuart** [comment]
Hi @Team1-epat, there was previously work in progress to support CKAN 2.10.x in this plugin, this has just been merged to master and tagged as 4.0.0. I'd recommend you try that out.
